Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "ubuntu/trusty64"
  c.vm.hostname = "microwave-rails-chef-microwave-rails-kitchen-box"
  c.vm.network(:forwarded_port, {:guest=>3000, :host=>4001})
  c.vm.network(:forwarded_port, {:guest=>9292, :host=>5001})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/varoske/Desktop/microwave-rails-chef/rails-app", "/home/vagrant/microwave-workspace", nil
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
